# Generated by Django 2.2.4 on 2020-08-23 22:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200822_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='upload/article/2020/05/1.jpg', upload_to='upload/article/%Y/%M', verbose_name='文章图片'),
        ),
    ]
