# Generated by Django 2.2.4 on 2020-08-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='留言时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('icon', models.CharField(max_length=256, verbose_name='头像')),
            ],
            options={
                'verbose_name': '留言表',
                'verbose_name_plural': '留言表',
                'db_table': 'message',
            },
        ),
    ]
